### ISSUE TITLE
最后总是显示核酸检测结果无效，怎么回事情呢

### ISSUE THREAD

**Issue by comeonsunny** [MasterKenway/DGUT-yqfkgo#1]
之前那个python的版本也是这个问题，大神这个背后的原因是是因为post的时候添加的confirm以后还不够吗？还是其他原因

**Comment by MasterKenway** [comment]
> ![image](https://user-images.githubusercontent.com/84911039/135618107-2939d852-2d93-40ff-9457-e26ed8fbab37.png)
> 
> 之前那个python的版本也是这个问题，大神这个背后的原因是是因为post的时候添加的confirm以后还不够吗？还是其他原因

confirm 解决的是异地服务器的问题

**Comment by comeonsunny** [comment]
我现在遇到的问题怎么解决比较合适呢

**Comment by comeonsunny** [comment]
还有这个图片里面有我的学号，可以方便删除一下吗

**Comment by MasterKenway** [comment]
> 我现在遇到的问题怎么解决比较合适呢
> 
> 

你之前是否有正常提交表单 我这里是正常的

**Comment by comeonsunny** [comment]
> > 我现在遇到的问题怎么解决比较合适呢
> 
> 你之前是否有正常提交表单 我这里是正常的
我之前提交的都是没有问题，并且我看了一下，有*的地方都已经填写了，难道是位置的问题的吗？
![image](https://user-images.githubusercontent.com/84911039/135630625-60efe14c-16ca-4cac-9dcf-735b519c3695.png)
这两个keys我没有用，

**Comment by MasterKenway** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> > > 我现在遇到的问题怎么解决比较合适呢
> 
> > 
> 
> > 你之前是否有正常提交表单 我这里是正常的
> 
> 我之前提交的都是没有问题，并且我看了一下，有*的地方都已经填写了，难道是位置的问题的吗？
> 
> ![image](https://user-images.githubusercontent.com/84911039/135630625-60efe14c-16ca-4cac-9dcf-735b519c3695.png)
> 
> 这两个keys我没有用，

你看下疫情防控页面的核酸字段是否正常 原因我在 discussion 已经解释过了

**Comment by comeonsunny** [comment]
> 你看下疫情防控页面的核酸字段是否正常 原因我在 discussion 已经解释过了
现在是我那个页面下没有“核酸”这个字段，我以为是表单的格式的问题，导致了那个接口不接收，
你说你的能够用，你是在东莞吗？显示你的位置在深圳呢？

**Comment by MasterKenway** [comment]
> > 你看下疫情防控页面的核酸字段是否正常 原因我在 discussion 已经解释过了
> > 现在是我那个页面下没有“核酸”这个字段，我以为是表单的格式的问题，导致了那个接口不接收，
> > 你说你的能够用，你是在东莞吗？显示你的位置在深圳呢？

服务不在东莞

**Comment by comeonsunny** [comment]
> > > 你看下疫情防控页面的核酸字段是否正常 原因我在 discussion 已经解释过了
> > > 现在是我那个页面下没有“核酸”这个字段，我以为是表单的格式的问题，导致了那个接口不接收，
> > > 你说你的能够用，你是在东莞吗？显示你的位置在深圳呢？
> 
> 服务不在东莞

哦，那我的位置本身在东莞，不应该提交的时候，更没有问题吗？我这个问题还有解吗？

**Comment by MasterKenway** [comment]
1. 所有提交的表单都是从你之前在官方页面提交的数据获取的
2. 你看到的修改字段只是表单中的部分 可以多阅读下代码
3. 地区问题和你这个问题无关
